micronaut:
  application:
    name: home-service
  server:
    port: 8082
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            validation:
              secret: DB4AEF4719809709E560ED8DE2F9C77B886B963B28BA20E9A8A621BBD4ABA599